project:
  type: book
  output-dir: _book

book:
  title: "Python para Ingeniería de Control"
  subtitle: "De Cero a Sistemas MIMO"
  author: "Ing. Yuri W. Ortiz E."
  date: today
  cover-image: cover.png
  chapters:
    - index.qmd
    - chapters/01-entorno.qmd
    - chapters/02-variables-tipos.qmd

execute:
  kernel: curso_python
  cache: false
  echo: true
  eval: true

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Mostrar código"
    number-sections: true
  pdf:
    documentclass: scrreprt
    geometry:
      - top=25mm
      - bottom=25mm
      - left=25mm
      - right=20mm
    fontsize: 11pt
    toc: true
    number-sections: true
    titlepage: true